apiVersion: 1

datasources:
  - name: Telemetry
    type: postgres
    uid: telemetry-db
    url: timescale:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: false